name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x, 21.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linter
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Run tests with coverage
      run: npm run test:coverage
      
    - name: Generate documentation
      run: npm run docs
      
    - name: Upload coverage to Codecov
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        fail_ci_if_error: false

  integration:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test CLI installation
      run: |
        npm pack
        npm install -g ./cidr-cli-*.tgz
        
    - name: Test CLI commands
      run: |
        cidr-cli --help
        cidr-cli contains 192.168.1.0/24 192.168.1.100
        cidr-cli contains 10.0.0.0/8,172.16.0.0/12 10.1.2.3
        ! cidr-cli contains 192.168.1.0/24 10.0.0.1  # Should fail
        
    - name: Test exit codes
      run: |
        set +e  # Don't exit on error
        
        # Should return 0 (success)
        cidr-cli contains 192.168.1.0/24 192.168.1.100
        if [ $? -ne 0 ]; then
          echo "Expected exit code 0 for IP in range"
          exit 1
        fi
        
        # Should return 1 (not found)
        cidr-cli contains 192.168.1.0/24 10.0.0.1
        if [ $? -ne 1 ]; then
          echo "Expected exit code 1 for IP not in range"
          exit 1
        fi
        
        # Should return 2 (error)
        cidr-cli contains invalid-cidr 192.168.1.1
        if [ $? -ne 2 ]; then
          echo "Expected exit code 2 for invalid CIDR"
          exit 1
        fi

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
    - name: Check for known vulnerabilities
      run: npx audit-ci --moderate