# The URL the site will be built for
base_url = "https://n-ae.github.io/portfolio"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "ntun"

taxonomies = [
  # You can enable/disable RSS
  {name = "categories", feed = true},
  {name = "tags", feed = true},
]
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "Nae"
author_image = "me.jpg"
city = "Istanbul"
years = "2024"

description = "Mythical Fountains"
job = "Software Engineer"

links = [
  {url = "https://github.com/n-ae", title = "n-ae", icon = "fab fa-github"},
  {url = "https://twitter.com/balisocialis", title = "twitter", icon = "fab fa-twitter"},
  {url = "https://www.linkedin.com/in/balii", title = "linkedin", icon = "fab fa-linkedin"},
#   {url = "mailto:", title = "", icon = "fas fa-envelope"},
]

# if you add languages, put your emoji flag on array
languages_flags = [
  "🇬🇧",
]
