# Simple workflow for deploying static content to GitHub Pages
name: Deploy Dev Blog

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "dev-blog/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    defaults:
      run:
        working-directory: ./dev-blog
    environment:
      name: github-pages
      # name: prod
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Theme
        uses: actions/checkout@v4
        with:
          path: ./dev-blog/themes/ntun
          repository: netoun/ntun
          # sparse-checkout: .
      - uses: taiki-e/install-action@v2
        with:
          tool: zola@0.17.1
      - name: Build release
        run: |
          zola build --base-url /${GITHUB_REPOSITORY#*/} -o dist
        shell: sh
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./dev-blog
          files: |
            ./dist
          outPath: ../dist.tar.gz
      - name: DEBUG
        run: |
          pwd
          ls -l1
          ls -l1 ./dev-blog/dist.tar.gz
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dev-blog/dist.tar.gz"
          # path: "./dev-blog/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
